### ISSUE TITLE
The Molecule YAML Patterns

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#279]
In order to make a molecule we need three patterns

# MoleculeEmpty YAML Pattern

# Atom YAML Pattern

# Bond YAML Pattern

**Comment by jimver04** [comment]
# Atom YAML patter

```
% ATOM
--- !u!1 &1239156494604166
GameObject:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 4294152572101188}
  - component: {fileID: 33554605904474542}
  - component: {fileID: 23360040833899088}
  - component: {fileID: 114082245266562788}
  - component: {fileID: 65652147814251746}
  m_Layer: 0
  m_Name: Natrium_transp
  m_TagString: natrium
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!4 &4294152572101188
Transform:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_LocalRotation: {x: -0, y: -0, z: -0, w: 1}
  m_LocalPosition: {x: -1.912218, y: -1.2362899, z: 0}
  m_LocalScale: {x: 1.0756785, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 4505150031759666}
  m_RootOrder: 1
  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}
--- !u!23 &23360040833899088
MeshRenderer:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Enabled: 1
  m_CastShadows: 1
  m_ReceiveShadows: 1
  m_DynamicOccludee: 1
  m_MotionVectors: 1
  m_LightProbeUsage: 1
  m_ReflectionProbeUsage: 1
  m_Materials:
  - {fileID: 2100000, guid: 493d40136ab47874c9edd8a4f7466d61, type: 2}
  m_StaticBatchInfo:
    firstSubMesh: 0
    subMeshCount: 0
  m_StaticBatchRoot: {fileID: 0}
  m_ProbeAnchor: {fileID: 0}
  m_LightProbeVolumeOverride: {fileID: 0}
  m_ScaleInLightmap: 1
  m_PreserveUVs: 1
  m_IgnoreNormalsForChartDetection: 0
  m_ImportantGI: 0
  m_StitchLightmapSeams: 0
  m_SelectedEditorRenderState: 3
  m_MinimumChartSize: 4
  m_AutoUVMaxDistance: 0.5
  m_AutoUVMaxAngle: 89
  m_LightmapParameters: {fileID: 0}
  m_SortingLayerID: 0
  m_SortingLayer: 0
  m_SortingOrder: 0  
--- !u!33 &33554605904474542
MeshFilter:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Mesh: {fileID: 10207, guid: 0000000000000000e000000000000000, type: 0}  
--- !u!65 &65652147814251746
BoxCollider:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Material: {fileID: 0}
  m_IsTrigger: 1
  m_Enabled: 1
  serializedVersion: 2
  m_Size: {x: 1, y: 1, z: 1}
  m_Center: {x: 0, y: 0, z: 0}  
--- !u!114 &114082245266562788
MonoBehaviour:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 32d9a756212078f4f95179bc563ee98c, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  placed: 0
  loopCheck: 0
```

1) Replace ```1239156494604166``` with `___[atom_fid]___`
2) Replace ```4294152572101188``` with `___[atom_transform]___`
3) Replace ```33554605904474542``` with `___[atom_sphere]___`
4) Repalce ```23360040833899088``` with `___[atom_mesh_renderer]___`
5) Replace ```65652147814251746``` with `___[atom_box_collider]___`
6) Replace ```Natrium_transp``` with `___[atom_name]___`  . '_transp'
7) Replace ```natrium``` with `___[atom_name_low_case]___
8) Replace ```m_LocalPosition: {x: -1.912218, y: -1.2362899, z: 0}``` with ```  m_LocalPosition: {x: ___[atom_pos_x]___, y: ___[atom_pos_y]___, z: ___[atom_pos_z]___}```
9) Replace ```493d40136ab47874c9edd8a4f7466d61``` with `___[atom_material]___`

**Comment by jimver04** [comment]
# Atom YAML pattern

```
% ATOM
--- !u!1 &1239156494604166
GameObject:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 4294152572101188}
  - component: {fileID: 33554605904474542}
  - component: {fileID: 23360040833899088}
  - component: {fileID: 114082245266562788}
  - component: {fileID: 65652147814251746}
  m_Layer: 0
  m_Name: Natrium_transp
  m_TagString: natrium
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!4 &4294152572101188
Transform:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_LocalRotation: {x: -0, y: -0, z: -0, w: 1}
  m_LocalPosition: {x: -1.912218, y: -1.2362899, z: 0}
  m_LocalScale: {x: 1.0756785, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 4505150031759666}
  m_RootOrder: 1
  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}
--- !u!23 &23360040833899088
MeshRenderer:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Enabled: 1
  m_CastShadows: 1
  m_ReceiveShadows: 1
  m_DynamicOccludee: 1
  m_MotionVectors: 1
  m_LightProbeUsage: 1
  m_ReflectionProbeUsage: 1
  m_Materials:
  - {fileID: 2100000, guid: 493d40136ab47874c9edd8a4f7466d61, type: 2}
  m_StaticBatchInfo:
    firstSubMesh: 0
    subMeshCount: 0
  m_StaticBatchRoot: {fileID: 0}
  m_ProbeAnchor: {fileID: 0}
  m_LightProbeVolumeOverride: {fileID: 0}
  m_ScaleInLightmap: 1
  m_PreserveUVs: 1
  m_IgnoreNormalsForChartDetection: 0
  m_ImportantGI: 0
  m_StitchLightmapSeams: 0
  m_SelectedEditorRenderState: 3
  m_MinimumChartSize: 4
  m_AutoUVMaxDistance: 0.5
  m_AutoUVMaxAngle: 89
  m_LightmapParameters: {fileID: 0}
  m_SortingLayerID: 0
  m_SortingLayer: 0
  m_SortingOrder: 0  
--- !u!33 &33554605904474542
MeshFilter:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Mesh: {fileID: 10207, guid: 0000000000000000e000000000000000, type: 0}  
--- !u!65 &65652147814251746
BoxCollider:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Material: {fileID: 0}
  m_IsTrigger: 1
  m_Enabled: 1
  serializedVersion: 2
  m_Size: {x: 1, y: 1, z: 1}
  m_Center: {x: 0, y: 0, z: 0}  
--- !u!114 &114082245266562788
MonoBehaviour:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1239156494604166}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 32d9a756212078f4f95179bc563ee98c, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  placed: 0
  loopCheck: 0
```

1) Replace ```1239156494604166``` with `___[atom_fid]___`
2) Replace ```4294152572101188``` with `___[atom_transform]___`
3) Replace ```33554605904474542``` with `___[atom_sphere]___`
4) Replace ```23360040833899088``` with `___[atom_mesh_renderer]___`
5) Replace ```65652147814251746``` with `___[atom_box_collider]___`
6) Replace ```Natrium_transp``` with `___[atom_name]___`  . '_transp'
7) Replace ```natrium``` with `___[atom_name_low_case]___
8) Replace ```m_LocalPosition: {x: -1.912218, y: -1.2362899, z: 0}``` with ```  m_LocalPosition: {x: ___[atom_pos_x]___, y: ___[atom_pos_y]___, z: ___[atom_pos_z]___}```
9) Replace ```493d40136ab47874c9edd8a4f7466d61``` with `___[atom_material]___`

**Comment by jimver04** [comment]
# Bond YAML Pattern

```
% BOND  
--- !u!1 &1438544309858614
GameObject:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 4113903089364838}
  - component: {fileID: 33645341749599482}
  - component: {fileID: 23960971567477714}
  m_Layer: 0
  m_Name: bond
  m_TagString: Bond
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!4 &4113903089364838
Transform:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1438544309858614}
  m_LocalRotation: {x: -0, y: -0, z: -0.7071068, w: 0.7071068}
  m_LocalPosition: {x: 0.607782, y: -1.2362897, z: 0}
  m_LocalScale: {x: 0.50000024, y: 2.3997338, z: 0.5}
  m_Children: []
  m_Father: {fileID: 4505150031759666}
  m_RootOrder: 0
  m_LocalEulerAnglesHint: {x: 0, y: 0, z: -90}
--- !u!23 &23960971567477714
MeshRenderer:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1438544309858614}
  m_Enabled: 1
  m_CastShadows: 1
  m_ReceiveShadows: 1
  m_DynamicOccludee: 1
  m_MotionVectors: 1
  m_LightProbeUsage: 1
  m_ReflectionProbeUsage: 1
  m_Materials:
  - {fileID: 10303, guid: 0000000000000000f000000000000000, type: 0}
  m_StaticBatchInfo:
    firstSubMesh: 0
    subMeshCount: 0
  m_StaticBatchRoot: {fileID: 0}
  m_ProbeAnchor: {fileID: 0}
  m_LightProbeVolumeOverride: {fileID: 0}
  m_ScaleInLightmap: 1
  m_PreserveUVs: 1
  m_IgnoreNormalsForChartDetection: 0
  m_ImportantGI: 0
  m_StitchLightmapSeams: 0
  m_SelectedEditorRenderState: 3
  m_MinimumChartSize: 4
  m_AutoUVMaxDistance: 0.5
  m_AutoUVMaxAngle: 89
  m_LightmapParameters: {fileID: 0}
  m_SortingLayerID: 0
  m_SortingLayer: 0
  m_SortingOrder: 0
--- !u!33 &33645341749599482
MeshFilter:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  m_GameObject: {fileID: 1438544309858614}
  m_Mesh: {fileID: 10206, guid: 0000000000000000e000000000000000, type: 0}
```

1) Replace : ```1438544309858614``` with `___[bond_fid]___`
2) Replace : ```4113903089364838``` with `___[bond_transform_fid]___`
3) Replace : ```33645341749599482``` with `___[bond_cylinder_fid]___`
4)

**Comment by jimver04** [comment]
# Material YAML Pattern

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!21 &2100000
Material:
  serializedVersion: 6
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_Name: Natrium_transp
  m_Shader: {fileID: 31, guid: 0000000000000000f000000000000000, type: 0}
  m_ShaderKeywords: _ALPHAPREMULTIPLY_ON
  m_LightmapFlags: 4
  m_EnableInstancingVariants: 0
  m_DoubleSidedGI: 0
  m_CustomRenderQueue: -1
  stringTagMap: {}
  disabledShaderPasses: []
  m_SavedProperties:
    serializedVersion: 3
    m_TexEnvs:
    - _BumpMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailAlbedoMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailNormalMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _EmissionMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MainTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MetallicGlossMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _OcclusionMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ParallaxMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _SpecGlossMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    m_Floats:
    - _BumpScale: 1
    - _Cutoff: 0.5
    - _DetailNormalMapScale: 1
    - _DstBlend: 10
    - _GlossMapScale: 1
    - _Glossiness: 0.4
    - _GlossyReflections: 1
    - _Metallic: 0
    - _Mode: 3
    - _OcclusionStrength: 1
    - _Parallax: 0.02
    - _Shininess: 0.5
    - _SmoothnessTextureChannel: 0
    - _SpecularHighlights: 1
    - _SrcBlend: 1
    - _UVSec: 0
    - _ZWrite: 0
    m_Colors:
    - _Color: {r: 0.5724139, g: 0, b: 1, a: 1}
    - _EmissionColor: {r: 0, g: 0, b: 0, a: 1}
    - _SpecColor: {r: 0.5, g: 0.5, b: 0.5, a: 0}
```

1) Replace `Natrium_transp` with `___[atom_name___`.'_transp'
2) Replace 

```_Color: {r: 0.5724139, g: 0, b: 1, a: 1}```

with 

```_Color: {r: ___[atom_color_r]___, g: ___[atom_color_g]___, b: ___[atom_color_b]___, a: 1}```

**Comment by jimver04** [comment]
The meta files should be also created for the material

```
fileFormatVersion: 2
guid: ___[molecule_mat_guid]___
timeCreated: 1519133976
licenseType: Free
NativeFormatImporter:
  externalObjects: {}
  mainObjectFileID: 0
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```

**Comment by jimver04** [comment]
# Molecule prefab meta file

```water.prefab.meta``` should be also generated


```
fileFormatVersion: 2
guid: ___[water_prefab_gui]___
timeCreated: 1518438644
licenseType: Free
NativeFormatImporter:
  externalObjects: {}
  mainObjectFileID: 100100000
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```
