### ISSUE TITLE
Wind Energy TEMPLATE YAML (S_Mountains)

### ISSUE THREAD

**Issue by PanMig** [DigiArt-project/wordpressunity3deditor#335]
# S_Mountains
```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
OcclusionCullingSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_OcclusionBakeSettings:
    smallestOccluder: 5
    smallestHole: 0.25
    backfaceThreshold: 100
  m_SceneGUID: 00000000000000000000000000000000
  m_OcclusionCullingData: {fileID: 0}
--- !u!104 &2
RenderSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 8
  m_Fog: 0
  m_FogColor: {r: 0.5147059, g: 0.5147059, b: 0.5147059, a: 1}
  m_FogMode: 3
  m_FogDensity: 0.01
  m_LinearFogStart: 0
  m_LinearFogEnd: 300
  m_AmbientSkyColor: {r: 0.36764705, g: 0.36764705, b: 0.36764705, a: 1}
  m_AmbientEquatorColor: {r: 0.114, g: 0.125, b: 0.133, a: 1}
  m_AmbientGroundColor: {r: 0.047, g: 0.043, b: 0.035, a: 1}
  m_AmbientIntensity: 0.23
  m_AmbientMode: 0
  m_SubtractiveShadowColor: {r: 0.42, g: 0.478, b: 0.627, a: 1}
  m_SkyboxMaterial: {fileID: 2100000, guid: 0b846be1b116429409a7669cacf2a62e, type: 2}
  m_HaloStrength: 0.317
  m_FlareStrength: 1
  m_FlareFadeSpeed: 3
  m_HaloTexture: {fileID: 0}
  m_SpotCookie: {fileID: 10001, guid: 0000000000000000e000000000000000, type: 0}
  m_DefaultReflectionMode: 0
  m_DefaultReflectionResolution: 256
  m_ReflectionBounces: 1
  m_ReflectionIntensity: 1
  m_CustomReflection: {fileID: 0}
  m_Sun: {fileID: 1806900448}
  m_IndirectSpecularColor: {r: 0, g: 0, b: 0, a: 1}
--- !u!157 &3
LightmapSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 11
  m_GIWorkflowMode: 1
  m_GISettings:
    serializedVersion: 2
    m_BounceScale: 1
    m_IndirectOutputScale: 1
    m_AlbedoBoost: 1
    m_TemporalCoherenceThreshold: 1
    m_EnvironmentLightingMode: 0
    m_EnableBakedLightmaps: 0
    m_EnableRealtimeLightmaps: 0
  m_LightmapEditorSettings:
    serializedVersion: 9
    m_Resolution: 2
    m_BakeResolution: 40
    m_TextureWidth: 1024
    m_TextureHeight: 1024
    m_AO: 0
    m_AOMaxDistance: 1
    m_CompAOExponent: 1
    m_CompAOExponentDirect: 0
    m_Padding: 2
    m_LightmapParameters: {fileID: 0}
    m_LightmapsBakeMode: 1
    m_TextureCompression: 1
    m_FinalGather: 0
    m_FinalGatherFiltering: 1
    m_FinalGatherRayCount: 256
    m_ReflectionCompression: 2
    m_MixedBakeMode: 2
    m_BakeBackend: 0
    m_PVRSampling: 1
    m_PVRDirectSampleCount: 32
    m_PVRSampleCount: 500
    m_PVRBounces: 2
    m_PVRFilterTypeDirect: 0
    m_PVRFilterTypeIndirect: 0
    m_PVRFilterTypeAO: 0
    m_PVRFilteringMode: 1
    m_PVRCulling: 1
    m_PVRFilteringGaussRadiusDirect: 1
    m_PVRFilteringGaussRadiusIndirect: 5
    m_PVRFilteringGaussRadiusAO: 2
    m_PVRFilteringAtrousPositionSigmaDirect: 0.5
    m_PVRFilteringAtrousPositionSigmaIndirect: 2
    m_PVRFilteringAtrousPositionSigmaAO: 1
    m_ShowResolutionOverlay: 1
  m_LightingDataAsset: {fileID: 0}
  m_UseShadowmask: 1
--- !u!196 &4
NavMeshSettings:
  serializedVersion: 2
  m_ObjectHideFlags: 0
  m_BuildSettings:
    serializedVersion: 2
    agentTypeID: 0
    agentRadius: 0.5
    agentHeight: 2
    agentSlope: 45
    agentClimb: 0.4
    ledgeDropHeight: 0
    maxJumpAcrossDistance: 0
    minRegionArea: 2
    manualCellSize: 0
    cellSize: 0.16666667
    manualTileSize: 0
    tileSize: 256
    accuratePlacement: 0
    debug:
      m_Flags: 0
  m_NavMeshData: {fileID: 0}
--- !u!1 &810014053
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 810014061}
  - component: {fileID: 810014060}
  - component: {fileID: 810014059}
  - component: {fileID: 810014058}
  - component: {fileID: 810014057}
  - component: {fileID: 810014054}
  m_Layer: 0
  m_Name: Camera
  m_TagString: MainCamera
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!114 &810014054
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 810014053}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 3fc73723c88eb074aa4782b094b16d58, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  panSpeed: 100
  zoomSpeed: 20
  zoomLimit: {x: 40, y: 70}
  enableBounds: 0
  heightLimit: {x: 150, y: 210}
  lenghtLimit: {x: -350, y: 700}
  widthLimit: {x: 540, y: 1000}
  rotationEnabled: 1
  rotateSpeed: 20
  rotationAngle: 30
--- !u!81 &810014057
AudioListener:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 810014053}
  m_Enabled: 1
--- !u!92 &810014058
Behaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 810014053}
  m_Enabled: 1
--- !u!124 &810014059
Behaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 810014053}
  m_Enabled: 1
--- !u!20 &810014060
Camera:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 810014053}
  m_Enabled: 1
  serializedVersion: 2
  m_ClearFlags: 1
  m_BackGroundColor: {r: 0.19215687, g: 0.3019608, b: 0.4745098, a: 0}
  m_NormalizedViewPortRect:
    serializedVersion: 2
    x: 0
    y: 0
    width: 1
    height: 1
  near clip plane: 0.3
  far clip plane: 3000
  field of view: 60
  orthographic: 0
  orthographic size: 50
  m_Depth: 0
  m_CullingMask:
    serializedVersion: 2
    m_Bits: 4294967295
  m_RenderingPath: -1
  m_TargetTexture: {fileID: 0}
  m_TargetDisplay: 0
  m_TargetEye: 3
  m_HDR: 1
  m_AllowMSAA: 1
  m_AllowDynamicResolution: 0
  m_ForceIntoRT: 0
  m_OcclusionCulling: 1
  m_StereoConvergence: 10
  m_StereoSeparation: 0.022
--- !u!4 &810014061
Transform:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 810014053}
  m_LocalRotation: {x: 0.17364816, y: 0, z: 0, w: 0.9848078}
  m_LocalPosition: {x: 0, y: 300, z: 0}
  m_LocalScale: {x: 1, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 0}
  m_RootOrder: 3
  m_LocalEulerAnglesHint: {x: 20, y: 0, z: 0}
--- !u!1001 &1515685078
Prefab:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Modification:
    m_TransformParent: {fileID: 0}
    m_Modifications:
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.z
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalRotation.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalRotation.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalRotation.z
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalRotation.w
      value: 1
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_RootOrder
      value: 1
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_AnchoredPosition.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_AnchoredPosition.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_SizeDelta.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_SizeDelta.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_AnchorMin.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_AnchorMin.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_AnchorMax.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_AnchorMax.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_Pivot.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_Pivot.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224162471157155074, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.x
      value: -86.6653
      objectReference: {fileID: 0}
    - target: {fileID: 224162471157155074, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.y
      value: -241.21
      objectReference: {fileID: 0}
    - target: {fileID: 224589604465816086, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.x
      value: -88.16527
      objectReference: {fileID: 0}
    - target: {fileID: 224589604465816086, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalPosition.y
      value: 356.28
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalScale.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalScale.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 224914459112912528, guid: 08a225d25044ba746a397bfad2e6b9ac,
        type: 2}
      propertyPath: m_LocalScale.z
      value: 0
      objectReference: {fileID: 0}
    m_RemovedComponents: []
  m_ParentPrefab: {fileID: 100100000, guid: 08a225d25044ba746a397bfad2e6b9ac, type: 2}
  m_IsPrefabParent: 0
--- !u!1 &1625518678
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 1625518681}
  - component: {fileID: 1625518680}
  - component: {fileID: 1625518679}
  m_Layer: 0
  m_Name: EventSystem
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!114 &1625518679
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1625518678}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 1077351063, guid: f70555f144d8491a825f0804e09c671c, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  m_HorizontalAxis: Horizontal
  m_VerticalAxis: Vertical
  m_SubmitButton: Submit
  m_CancelButton: Cancel
  m_InputActionsPerSecond: 10
  m_RepeatDelay: 0.5
  m_ForceModuleActive: 0
--- !u!114 &1625518680
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1625518678}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: -619905303, guid: f70555f144d8491a825f0804e09c671c, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  m_FirstSelected: {fileID: 0}
  m_sendNavigationEvents: 1
  m_DragThreshold: 5
--- !u!4 &1625518681
Transform:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1625518678}
  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}
  m_LocalPosition: {x: 0, y: 0, z: 0}
  m_LocalScale: {x: 1, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 0}
  m_RootOrder: 2
  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}
--- !u!1 &1806900447
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 1806900449}
  - component: {fileID: 1806900448}
  m_Layer: 0
  m_Name: Directional light
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!108 &1806900448
Light:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1806900447}
  m_Enabled: 1
  serializedVersion: 8
  m_Type: 1
  m_Color: {r: 1, g: 1, b: 1, a: 1}
  m_Intensity: 1.8
  m_Range: 10
  m_SpotAngle: 30
  m_CookieSize: 10
  m_Shadows:
    m_Type: 0
    m_Resolution: -1
    m_CustomResolution: -1
    m_Strength: 1
    m_Bias: 0.05
    m_NormalBias: 0.4
    m_NearPlane: 0.2
  m_Cookie: {fileID: 0}
  m_DrawHalo: 0
  m_Flare: {fileID: 0}
  m_RenderMode: 0
  m_CullingMask:
    serializedVersion: 2
    m_Bits: 4294967295
  m_Lightmapping: 4
  m_AreaSize: {x: 1, y: 1}
  m_BounceIntensity: 1
  m_ColorTemperature: 6570
  m_UseColorTemperature: 0
  m_ShadowRadius: 0
  m_ShadowAngle: 0
--- !u!4 &1806900449
Transform:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1806900447}
  m_LocalRotation: {x: 0.40821788, y: -0.23456968, z: 0.10938163, w: 0.8754261}
  m_LocalPosition: {x: 4047.9255, y: 1415.0872, z: 479.21704}
  m_LocalScale: {x: 1, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 0}
  m_RootOrder: 0
  m_LocalEulerAnglesHint: {x: 50, y: -30, z: 0}
```

**Comment by PanMig** [comment]
# Marker YAML

```
--- !u!1001 &___[marker_fid]___
Prefab:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Modification:
    m_TransformParent: {fileID: 0}
    m_Modifications:
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalPosition.x
      value: -0
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalPosition.y
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalPosition.z
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalRotation.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalRotation.y
      value: -0
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalRotation.z
      value: -0
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_LocalRotation.w
      value: 1
      objectReference: {fileID: 0}
    - target: {fileID: 4432963095571188, guid: ___[marker_obj_guid]___, type: 2}
      propertyPath: m_RootOrder
      value: 4
      objectReference: {fileID: 0}
    m_RemovedComponents:
    - {fileID: 114707447727845176, guid: ___[marker_obj_guid]___, type: 2}
    - {fileID: 65823032349800856, guid: ___[marker_obj_guid]___, type: 2}
  m_ParentPrefab: {fileID: 100100000, guid: ___[marker_obj_guid]___, type: 2}
  m_IsPrefabParent: 0
--- !u!1 &___[marker_fid + 1]___ stripped
GameObject:
  m_PrefabParentObject: {fileID: 1821963947913140, guid: ___[marker_obj_guid]___,
    type: 2}
  m_PrefabInternal: {fileID: ___[marker_fid]___}
--- !u!65 &___[marker_fid + 2]___
BoxCollider:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: ___[marker_fid + 1]___}
  m_Material: {fileID: 0}
  m_IsTrigger: 0
  m_Enabled: 1
  serializedVersion: 2
  m_Size: {x: 21.664255, y: 32.9558, z: 11.762192}
  m_Center: {x: -0.081339836, y: 15.977903, z: 2.4025803}
--- !u!114 &___[marker_fid + 3]___
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: ___[marker_fid + 1]___}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: fcbd356492004d948aab39bf4dd5a279, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  infoPanel: {fileID: 1515685079}
  pointerSprites: []
  subAreaType: 1
  subAreaIndex: 1
  PenaltyForArchaiological: 1
  PenaltyForNature: 1
  CostForDistFromHV: 1
```

1. Replace `___[marker_fid]___`
2. Replace `___[marker_fid + 1]___`
3. Replace `___[marker_fid + 2]___`  (box collider)
4. Replace `___[marker_fid + 3]___`  (monobehaviour)

**Comment by PanMig** [comment]
# Terrain Yaml
```
--- !u!1001 &2104841023
Prefab:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Modification:
    m_TransformParent: {fileID: 0}
    m_Modifications:
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalPosition.x
      value: -2.2682128
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalPosition.y
      value: -1.6764753
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalPosition.z
      value: 1.3828073
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalRotation.x
      value: 0
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalRotation.y
      value: -0
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalRotation.z
      value: -0
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalRotation.w
      value: 1
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_RootOrder
      value: 1
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalScale.x
      value: 1.01
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalScale.y
      value: 1.01
      objectReference: {fileID: 0}
    - target: {fileID: 400000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_LocalScale.z
      value: 1.01
      objectReference: {fileID: 0}
    - target: {fileID: 100002, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
      propertyPath: m_Name
      value: Lab2
      objectReference: {fileID: 0}
    m_RemovedComponents: []
  m_ParentPrefab: {fileID: 100100000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
  m_IsPrefabParent: 0
--- !u!1 &2104841024 stripped
GameObject:
  m_PrefabParentObject: {fileID: 100002, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
  m_PrefabInternal: {fileID: 2104841023}
--- !u!64 &2104841025
MeshCollider:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 2104841024}
  m_Material: {fileID: 0}
  m_IsTrigger: 0
  m_Enabled: 1
  serializedVersion: 3
  m_Convex: 0
  m_CookingOptions: 14
  m_SkinWidth: 0.01
  m_Mesh: {fileID: 4300000, guid: 483b3742c391f3c4496b09c2c0eb35c6, type: 3}
```

Replacements
1.   `2104841023` with `___[room_fid]___`
2.   `2104841024`  with `___[room_mesh_fid]___`    (= `___[room_fid]___  + 1`)      
3.   `2104841025` with `___[room_mesh_collider_fid]___`  (= `___[room_fid]___  + 2`)

4.   `483b3742c391f3c4496b09c2c0eb35c6` with `___[room_obj_guid]___`

5.   `propertyPath: m_LocalPosition.x`      ....    rotations and scale in y,z
     value: 0

with
`___[room_position_x]___, ___[room_position_y]___, ___[room_position_z]___,
___[room_rotation_x]___, ___[room_rotation_y]___, ___[room_rotation_z]___, ___[room_rotation_w]___,
___[room_scale_x]___, ___[room_scale_y]___, ___[room_scale_z]___`

6.   `Lab2`  with `___[room_title]___`
