### ISSUE TITLE
Wind Energy: Scene Selector is put first

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#354]
Stathi Please fix so that Main menu is first in Wind Energy

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!1045 &1
EditorBuildSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Scenes:
  - enabled: 1
    path: Assets/scenes/S_SceneSelector.unity
  - enabled: 1
    path: Assets/scenes/Stage3(Plains).unity
  - enabled: 1
    path: Assets/scenes/Stage3(Mountains).unity
  - enabled: 1
    path: Assets/scenes/Stage3(Seashore).unity
  - enabled: 1
    path: Assets/scenes/S_Stats.unity
  - enabled: 1
    path: Assets/scenes/S_TurbineSelection.unity
  - enabled: 1
    path: Assets/scenes/S_MainMenu.unity
  - enabled: 1
    path: Assets/scenes/S_Help.unity
  - enabled: 1
    path: Assets/scenes/S_Login.unity
  - enabled: 1
    path: Assets/scenes/S_Credits.unity
  - enabled: 1
    path: Assets/scenes/S_Fields.unity
  - enabled: 1
    path: Assets/scenes/S_Seashore.unity
  - enabled: 1
    path: Assets/scenes/S_Mountains.unity
```
